name: ci/cd

on:
  push:
    tags:
      - '*'

jobs:

  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: main
      env:
        REGISTRY: registry.digitalocean.com
        PREFIX:   registry-carbon-cc/www-at-jhord
      run: |
        TAG=$(echo $GITHUB_REF | cut -d '/' -f 3)
        docker login ${REGISTRY} --username ${{ secrets.DO_TOKEN }} --password ${{ secrets.DO_TOKEN }}
        docker build -f Dockerfile.http -t ${REGISTRY}/${PREFIX}-http:${TAG} .
        docker push ${REGISTRY}/${PREFIX}:-http${TAG}
        docker build -f Dockerfile.grpc -t ${REGISTRY}/${PREFIX}-grpc:${TAG} .
        docker push ${REGISTRY}/${PREFIX}-grpc:${TAG}
